version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mobiauto-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mobiauto
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: mobiauto-app
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mobiauto

volumes:
  mongo_data:
