server:
  port: 8080

spring:
  application:
    name: mobiauto-backend
    uuid-representation: standard
    auto-index-creation: true
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/mobiauto}

logging:
  level:
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              MongoTemplate: INFO
